version: '3.7'

networks:
  my_network:
    name: 'my_network'

services:
  postgis:
    container_name: 'postgis_container'
    image: pgrouting/pgrouting:16-3.4-3.6.1
    networks:
      - my_network
    volumes:
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/db/:/db/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  python_container:
    container_name: 'python_container'
    image: andrejreznik/python-gdal:py3.10.0-gdal3.2.3
    tty: true
    stdin_open: true
    networks:
      - my_network
    volumes:
      - ./funciones/:/funciones
      - ./data/:/data
      - ./scripts:/scripts
      - ./.env:/.env
    depends_on:
      - postgis
    command: sh -c "pip install -r /scripts/python/requirements.txt && python /scripts/python/init.py"
    


